shawee_test_api:
    resource: "@ShaweeTestApiBundle/Controller/"
    type:     annotation
    prefix:   /

tapioca_design_class_live_gnv:
    resource: "@TapiocaDesignClassLiveGnvBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api

