<?php

namespace Proxies\__CG__\TapiocaDesign\ClassLiveGnvBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Performance extends \TapiocaDesign\ClassLiveGnvBundle\Entity\Performance implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'id', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'work', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'place', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'datePerformance', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'ticketWebsite', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'ticketEmail', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'ticketTelephone', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'ticketPriceLowest', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'ticketPriceHighest');
        }

        return array('__isInitialized__', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'id', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'work', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'place', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'datePerformance', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'ticketWebsite', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'ticketEmail', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'ticketTelephone', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'ticketPriceLowest', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Performance' . "\0" . 'ticketPriceHighest');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Performance $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePerformance($datePerformance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePerformance', array($datePerformance));

        return parent::setDatePerformance($datePerformance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePerformance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePerformance', array());

        return parent::getDatePerformance();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketWebsite($ticketWebsite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketWebsite', array($ticketWebsite));

        return parent::setTicketWebsite($ticketWebsite);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketWebsite', array());

        return parent::getTicketWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketEmail($ticketEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketEmail', array($ticketEmail));

        return parent::setTicketEmail($ticketEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketEmail', array());

        return parent::getTicketEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketTelephone($ticketTelephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketTelephone', array($ticketTelephone));

        return parent::setTicketTelephone($ticketTelephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketTelephone', array());

        return parent::getTicketTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketPriceLowest($ticketPriceLowest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketPriceLowest', array($ticketPriceLowest));

        return parent::setTicketPriceLowest($ticketPriceLowest);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketPriceLowest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketPriceLowest', array());

        return parent::getTicketPriceLowest();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketPriceHighest($ticketPriceHighest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketPriceHighest', array($ticketPriceHighest));

        return parent::setTicketPriceHighest($ticketPriceHighest);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketPriceHighest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketPriceHighest', array());

        return parent::getTicketPriceHighest();
    }

    /**
     * {@inheritDoc}
     */
    public function setWork(\TapiocaDesign\ClassLiveGnvBundle\Entity\Work $work = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWork', array($work));

        return parent::setWork($work);
    }

    /**
     * {@inheritDoc}
     */
    public function getWork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWork', array());

        return parent::getWork();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlace(\TapiocaDesign\ClassLiveGnvBundle\Entity\Place $place = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlace', array($place));

        return parent::setPlace($place);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlace', array());

        return parent::getPlace();
    }

}
