

acme_demo_city_all:
    pattern:  /city
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:CityRest:all, _format: ~ }
    requirements:
        _method: GET

acme_demo_city_get:
    pattern:  /city/{id}
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:CityRest:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

TD_CLG_worksOrderedByFirstPerformance:
    pattern:  /city/{city_id}/worksOrderedByFirstPerformance
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:WorkRest:worksOrderedByFirstPerformance, _format: ~ }
    requirements:
        _method: GET
        city_id: "\d+"

TD_CLG_work:
    pattern:  /work/{work_id}
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:WorkRest:work, _format: ~ }
    requirements:
        _method: GET
        work_id: "\d+"

TD_CLG_placesByCity:
    pattern:  /city/{city_id}/places
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:PlaceRest:placesByCity, _format: ~ }
    requirements:
        _method: GET
        city_id: "\d+"

TD_CLG_place:
    pattern:  /place/{place_id}
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:PlaceRest:place, _format: ~ }
    requirements:
        _method: GET
        place_id: "\d+"





