<?php

namespace Proxies\__CG__\TapiocaDesign\ClassLiveGnvBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Work extends \TapiocaDesign\ClassLiveGnvBundle\Entity\Work implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'id', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'performances', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'name', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'name_url', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'composer', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'interpreter', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'director', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'style', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'description', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'imageMain');
        }

        return array('__isInitialized__', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'id', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'performances', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'name', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'name_url', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'composer', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'interpreter', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'director', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'style', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'description', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Work' . "\0" . 'imageMain');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Work $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlName($url_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlName', array($url_name));

        return parent::setUrlName($url_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlName', array());

        return parent::getUrlName();
    }

    /**
     * {@inheritDoc}
     */
    public function setComposer($composer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComposer', array($composer));

        return parent::setComposer($composer);
    }

    /**
     * {@inheritDoc}
     */
    public function getComposer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComposer', array());

        return parent::getComposer();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterpreter($interpreter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterpreter', array($interpreter));

        return parent::setInterpreter($interpreter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterpreter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterpreter', array());

        return parent::getInterpreter();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirector($director)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirector', array($director));

        return parent::setDirector($director);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirector', array());

        return parent::getDirector();
    }

    /**
     * {@inheritDoc}
     */
    public function setStyle($style)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStyle', array($style));

        return parent::setStyle($style);
    }

    /**
     * {@inheritDoc}
     */
    public function getStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStyle', array());

        return parent::getStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageMain($imageMain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageMain', array($imageMain));

        return parent::setImageMain($imageMain);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageMain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageMain', array());

        return parent::getImageMain();
    }

    /**
     * {@inheritDoc}
     */
    public function addPerformance(\TapiocaDesign\ClassLiveGnvBundle\Entity\Performance $performances)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPerformance', array($performances));

        return parent::addPerformance($performances);
    }

    /**
     * {@inheritDoc}
     */
    public function removePerformance(\TapiocaDesign\ClassLiveGnvBundle\Entity\Performance $performances)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePerformance', array($performances));

        return parent::removePerformance($performances);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerformances()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerformances', array());

        return parent::getPerformances();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
