<?php

namespace Proxies\__CG__\TapiocaDesign\ClassLiveGnvBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Place extends \TapiocaDesign\ClassLiveGnvBundle\Entity\Place implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'id', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'city', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'performances', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'nameUrl', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'nameShort', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'nameFr', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'nameEn', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'address', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'telephone', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'email', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'mapLatitude', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'mapLongitude', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'googleMapRef', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'website', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'imagePlaceMain');
        }

        return array('__isInitialized__', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'id', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'city', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'performances', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'nameUrl', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'nameShort', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'nameFr', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'nameEn', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'address', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'telephone', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'email', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'mapLatitude', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'mapLongitude', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'googleMapRef', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'website', '' . "\0" . 'TapiocaDesign\\ClassLiveGnvBundle\\Entity\\Place' . "\0" . 'imagePlaceMain');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Place $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameFr($nameFr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameFr', array($nameFr));

        return parent::setNameFr($nameFr);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameFr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameFr', array());

        return parent::getNameFr();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameEn($nameEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameEn', array($nameEn));

        return parent::setNameEn($nameEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameEn', array());

        return parent::getNameEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMapLatitude($mapLatitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMapLatitude', array($mapLatitude));

        return parent::setMapLatitude($mapLatitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getMapLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMapLatitude', array());

        return parent::getMapLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setMapLongitude($mapLongitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMapLongitude', array($mapLongitude));

        return parent::setMapLongitude($mapLongitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getMapLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMapLongitude', array());

        return parent::getMapLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameUrl($nameUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameUrl', array($nameUrl));

        return parent::setNameUrl($nameUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameUrl', array());

        return parent::getNameUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameShort($nameShort)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameShort', array($nameShort));

        return parent::setNameShort($nameShort);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameShort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameShort', array());

        return parent::getNameShort();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoogleMapRef($googleMapRef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoogleMapRef', array($googleMapRef));

        return parent::setGoogleMapRef($googleMapRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoogleMapRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogleMapRef', array());

        return parent::getGoogleMapRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', array($website));

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', array());

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagePlaceMain($imagePlaceMain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagePlaceMain', array($imagePlaceMain));

        return parent::setImagePlaceMain($imagePlaceMain);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagePlaceMain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagePlaceMain', array());

        return parent::getImagePlaceMain();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(\TapiocaDesign\ClassLiveGnvBundle\Entity\City $city = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function addPerformance(\TapiocaDesign\ClassLiveGnvBundle\Entity\Performance $performances)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPerformance', array($performances));

        return parent::addPerformance($performances);
    }

    /**
     * {@inheritDoc}
     */
    public function removePerformance(\TapiocaDesign\ClassLiveGnvBundle\Entity\Performance $performances)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePerformance', array($performances));

        return parent::removePerformance($performances);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerformances()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerformances', array());

        return parent::getPerformances();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
