

acme_demo_city_all:
    pattern:  /city
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:CityRest:all, _format: ~ }
    requirements:
        _method: GET

acme_demo_city_get:
    pattern:  /city/{id}
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:CityRest:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

TD_CLG_worksOrderedByFirstPerformance:
    pattern:  /city/{city_id}/worksOrderedByFirstPerformance
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:WorkRest:worksOrderedByFirstPerformance, _format: ~ }
    requirements:
        _method: GET
        city_id: "\d+"

TD_CLG_work:
    pattern:  /work/{work_id}
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:WorkRest:work, _format: ~ }
    requirements:
        _method: GET
        work_id: "\d+"




TD_CLG_placesByCity:
    pattern:  /city/{city_id}/places
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:PlaceRest:placesByCity, _format: ~ }
    requirements:
        _method: GET
        city_id: "\d+"

TD_CLG_placesWithPerformancesByCity:
    pattern:  /city/{city_id}/placesWithPerformances
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:PlaceRest:placesWithPerformancesByCity, _format: ~ }
    requirements:
        _method: GET
        city_id: "\d+"

TD_CLG_place:
    pattern:  /place/{place_id}
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:PlaceRest:place, _format: ~ }
    requirements:
        _method: GET
        place_id: "\d+"

TD_CLG_worksByPlace:
    pattern:  /place/{place_id}/works
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:WorkRest:worksByPlace, _format: ~ }
    requirements:
        _method: GET
        work_id: "\d+"

TD_CLG_performance:
    pattern:  /performance/{performance_id}
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:PerformanceRest:performance, _format: ~ }
    requirements:
        _method: GET
        performance_id: "\d+"

TD_CLG_performancesByPlace:
    pattern:  /place/{place_id}/performances
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:PerformanceRest:performancesByPlace, _format: ~ }
    requirements:
        _method: GET
        place_id: "\d+"

TD_CLG_performancesByPlaceGroupedByWork:
    pattern:  /place/{place_id}/performancesGroupedByWork
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:PerformanceRest:performancesByPlaceGroupedByWork, _format: ~ }
    requirements:
        _method: GET
        place_id: "\d+"

TD_CLG_performancesByWork:
    pattern:  /work/{work_id}/performances
    defaults: { _controller: TapiocaDesignClassLiveGnvBundle:PerformanceRest:performancesByWork, _format: ~ }
    requirements:
        _method: GET
        work_id: "\d+"

